Repository codestates/Shall-We-Health, pull requests merged in 2022-01, with the labels that each got.

#346 [Client] / #345 / index.html KAKAO API 환경변수 변경
  client/public/index.html
  client/src/components/FindPw/UpdatePw.css
  client/src/components/FindPw/UpdatePw.js
  client/src/pages/SignUp.js
Labels: Client, C: 0.5h

#349 [Client] / #348 / design: NavigationBar 다크모드 로고 이미지 변경
  client/src/App.css
  client/src/pages/NavigationBar.css
  client/src/pages/NavigationBar.js
Labels: C: 1h

#351 [Refactor] / #350 / 어드민 버그해결 및 mysql event schedule 추가
  server/controllers/admin/index.js
  server/controllers/admin/issueList.js
  server/controllers/admin/postList.js
  server/controllers/admin/userList.js
  server/controllers/mypage/index.js
Labels: refactor

#354 Refactor: 서버 API path 복수형으로 변경(#353)
  client/src/App.js
  client/src/components/AdminPage/AdminIssue.js
  client/src/components/AdminPage/AdminMath.js
  client/src/components/AdminPage/AdminUser.js
  client/src/components/FindPw/UpdatePw.js
  client/src/components/MyPage/Issue.js
  client/src/components/MyPage/ModifyUserInfo.js
  client/src/components/MyPage/MyLog.js
  client/src/components/MyPage/Withdraw.js
  client/src/components/SignUp/Kakao.js
  client/src/components/SignUp/VerifyEmail.js
  client/src/components/View.js/Chat.js
  client/src/components/etc/App.js
  client/src/pages/AdminPage.js
  client/src/pages/Board.js
  client/src/pages/FindPartner.js
  client/src/pages/FindPartnerModify.js
  client/src/pages/FindPw.js
  client/src/pages/Login.js
  client/src/pages/NaverLogin.js
  client/src/pages/NavigationBar.js
  client/src/pages/SignUp.js
  client/src/pages/View.js
  server/controllers/admin/index.js
  server/controllers/admin/issueList.js
  server/controllers/admin/userList.js
  server/controllers/chat/index.js
  server/controllers/mypage/index.js
  server/controllers/post/content.js
  server/controllers/post/index.js
  server/controllers/post/match.js
  server/controllers/user/auth.js
  server/controllers/user/emailVerification.js
  server/controllers/user/info.js
  server/controllers/user/kakao.js
  server/controllers/user/login.js
  server/controllers/user/naver.js
  server/controllers/user/passwordVerification.js
  server/controllers/user/signup.js
  server/index.js
  server/utils/validation.js
Labels: E : 0.5h

#358 [Refactor] 테이블 및 데이터 삭제오류 해결
  server/migrations/20211125075700-create-post.js
  server/migrations/20211125075758-create-chat.js
  server/migrations/20211125075944-create-thumbsup.js
  server/migrations/20211125080037-create-issue.js
  server/models/chat.js
  server/models/user.js
Labels: bug
